host: "127.0.0.1"
port: 3000
lb_strategy: "weighted_round_robin"
health_check_interval: 10
backends:
  - name: "backend-1"
    url: "http://127.0.0.1:8081"
    weight: 1
  - name: "backend-2" 
    url: "http://127.0.0.1:8082"
    weight: 1
  - name: "backend-3"
    url: "http://127.0.0.1:8083"
    weight: 2
   
